-- Cập nhật và chuẩn hóa bảng dot_dangky cho MySQL Production/Online

CREATE TABLE IF NOT EXISTS `dot_dangky` (
    `MaDot` INT NOT NULL AUTO_INCREMENT,
    `TenDot` VARCHAR(255) NOT NULL,
    `MoTa` TEXT DEFAULT NULL,
    `HocKy` VARCHAR(50) NOT NULL,
    `NamHoc` VARCHAR(50) DEFAULT NULL,
    `NienKhoa` VARCHAR(50) NOT NULL,
    `NgayTao` DATETIME NOT NULL,
    `NgayDong` DATETIME NOT NULL,
    `TrangThai` VARCHAR(50) DEFAULT 'Mo',
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`MaDot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `dot_dangky`
ADD COLUMN IF NOT EXISTS `MoTa` TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `NamHoc` VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS `NienKhoa` VARCHAR(50) DEFAULT NULL;

ALTER TABLE `dot_dangky`
MODIFY COLUMN `TrangThai` VARCHAR(50) DEFAULT 'Mo';
